#!/bin/sh

# Couchbase Server start script. 

set -e

if [ "$1" = 'couchbase-server' ]
then
    # Create directories where couchbase stores its data
    cd /opt/couchbase
    mkdir -p var/lib/couchbase \
        var/lib/couchbase/config \
        var/lib/couchbase/data \
        var/lib/couchbase/stats \
        var/lib/couchbase/logs \
        var/lib/moxi

    # Start couchbase
    echo "Starting Couchbase Server -- Web UI available at http://<ip>:8091"
fi

exec "$@"
